name: Super-Linter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
        
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - run: java -cp java
    
    - name: run pom
      working-directory: github-actions-java-maven
      run: mvn -B pom.xml compile
        
    - name: java version
      run: javac -version
      

      
        
 
        
  
